### ISSUE TITLE
Checksum does not match: stored 270509511 vs. calculated on the restored bytes 2065416399

### ISSUE THREAD

**Issue by Muennighoff** [Akashtyagi08/Pretrained-im2txt-single_instance#6]
Thanks for the great repo - I am running into the checksum issue as some others. Is the file perhaps corrupted or any of my code wrong? Thanks a lot for any help! 

Here is my code: 

```
!pip install tensorflow==1.15
import nltk
nltk.download('punkt')
import tensorflow

!pip show tensorflow
!pip show numpy
!python --version

!cd ../; git clone https://github.com/Akashtyagi08/Pretrained-im2txt-single_instance.git
!cd ../Pretrained-im2txt-single_instance; python im2txt.py
```

Output:

Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: opt-einsum, astor, keras-preprocessing, six, gast, protobuf, tensorflow-estimator, wheel, tensorboard, grpcio, absl-py, numpy, termcolor, keras-applications, wrapt, google-pasta
Required-by: fancyimpute

Name: numpy
Version: 1.18.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org

Python 3.7.6

Cloning into 'Pretrained-im2txt-single_instance'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 69 (delta 14), reused 48 (delta 3), pack-reused 0
Unpacking objects: 100% (69/69), done.
Test  ['a', '<S>', '</S>', '.', 'on']
2020-07-28 10:50:19.062490: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib
2020-07-28 10:50:19.062560: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-28 10:50:19.062590: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (1c9ec14772c0): /proc/driver/nvidia/version does not exist
2020-07-28 10:50:19.063022: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-28 10:50:19.072729: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200195000 Hz
2020-07-28 10:50:19.073427: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56528827dd10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-28 10:50:19.073521: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-28 10:50:19.801571: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: Checksum does not match: stored 270509511 vs. calculated on the restored bytes 2065416399
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 270509511 vs. calculated on the restored bytes 2065416399
	 [[{{node save/RestoreV2}}]]

**Comment by Akashtyagi** [comment]
This occurs when the due to difference in TensorFlow version's. 

Different checksum means the data was trained on a specific version of TensorFlow, thus the resultant file contains that specific checksum value. But when you are trying to read it now, TensorFlow version doesn't match.

I had manually edited the checkpoints to fix this issue and and uploaded the correct version here. Its was working fine on my machine. Unfortunately, currently I am not using the same environment

You can try looking into the parent Repo issues, this has been addressed in past. You will definitely find its solution.

**Comment by Akashtyagi** [comment]
Make sure you follow the readme steps carefully and install specific version.

Maybe this helps [#Issue4](https://github.com/Akashtyagi08/Pretrained-im2txt-single_instance/issues/4)

**Comment by Muennighoff** [comment]
> This occurs when the due to difference in TensorFlow version's.
> 
> Different checksum means the data was trained on a specific version of TensorFlow, thus the resultant file contains that specific checksum value. But when you are trying to read it now, TensorFlow version doesn't match.
> 
> I had manually edited the checkpoints to fix this issue and and uploaded the correct version here. Its was working fine on my machine. Unfortunately, currently I am not using the same environment
> 
> You can try looking into the parent Repo issues, this has been addressed in past. You will definitely find its solution.

Thanks for getting back to me. I see, but I am installing tensorflow 1.15 as recommended - Should I try a different TF version?

**Comment by Akashtyagi** [comment]
Hey @Muennighoff , If you were able to resolve this issue, can you please share your solution here.
